FROM node:14

WORKDIR /app/frontend

COPY frontend/package.json ./

RUN npm install

COPY /frontend ./

ARG REACT_APP_KAKAO_MAP_API_KEY

ENV REACT_APP_KAKAO_MAP_API_KEY=$REACT_APP_KAKAO_MAP_API_KEY

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]