FROM python:3.11

WORKDIR /app/backend

COPY backend/pyproject.toml ./

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="${PATH}:/root/.local/bin"

RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

COPY / ./

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]