from django.db import models

# Create your models here.
class HospitalBasic(models.Model):
    hpid = models.CharField(max_length = 10, primary_key = True)
    phpid = models.CharField(max_length = 10)
    duty_emcls = models.CharField(max_length = 4)
    duty_emcls_name = models.CharField(max_length = 50)
    duty_addr = models.CharField(max_length = 255)
    duty_name = models.CharField(max_length = 255)
    duty_tel1 = models.CharField(max_length = 14)
    duty_tel3 = models.CharField(max_length = 14)
    wgs_84_lon = models.DecimalField(max_digits=17, decimal_places=14)
    wgs_84_lat = models.DecimalField(max_digits=17, decimal_places=14)
    center_type = models.CharField(max_length = 1)
    
    class Meta:
        db_table = "HOSPITAL_BASIC_INFO"
        
class HospitalDetail(models.Model):
    hpid = models.CharField(max_length = 10, primary_key = True)
    post_cdn1 = models.CharField(max_length = 3)
    post_cdn2 = models.CharField(max_length = 3)
    hvec = models.IntegerField()
    hvoc = models.IntegerField()
    hvcc = models.IntegerField()
    hvncc = models.IntegerField()
    hvccc = models.IntegerField()
    hvicc = models.IntegerField()
    hvgc = models.IntegerField()
    duty_hayn = models.CharField(max_length = 1)
    duty_hano = models.IntegerField()
    duty_inf = models.CharField(max_length = 300)
    duty_map_img = models.CharField(max_length = 100)
    duty_eryn = models.CharField(max_length = 1)
    duty_time_1c = models.CharField(max_length = 4)
    duty_time_2c = models.CharField(max_length = 4)
    duty_time_3c = models.CharField(max_length = 4)
    duty_time_4c = models.CharField(max_length = 4)
    duty_time_5c = models.CharField(max_length = 4)
    duty_time_6c = models.CharField(max_length = 4)
    duty_time_7c = models.CharField(max_length = 4)
    duty_time_8c = models.CharField(max_length = 4)
    duty_time_1s = models.CharField(max_length = 4)
    duty_time_2s = models.CharField(max_length = 4)
    duty_time_3s = models.CharField(max_length = 4)
    duty_time_4s = models.CharField(max_length = 4)
    duty_time_5s = models.CharField(max_length = 4)
    duty_time_6s = models.CharField(max_length = 4)
    duty_time_7s = models.CharField(max_length = 4)
    duty_time_8s = models.CharField(max_length = 4)
    mkioskty25 = models.CharField(max_length = 1)
    mkioskty1 = models.CharField(max_length = 1)
    mkioskty2 = models.CharField(max_length = 1)
    mkioskty3 = models.CharField(max_length = 1)
    mkioskty4 = models.CharField(max_length = 1)
    mkioskty5 = models.CharField(max_length = 1)
    mkioskty6 = models.CharField(max_length = 1)
    mkioskty7 = models.CharField(max_length = 1)
    mkioskty8 = models.CharField(max_length = 1)
    mkioskty9 = models.CharField(max_length = 1)
    mkioskty10 = models.CharField(max_length = 1)
    mkioskty11 = models.CharField(max_length = 1)
    dgid_id_name = models.CharField(max_length = 50)
    hpbdn = models.IntegerField()
    hpccuyn = models.IntegerField()
    hpcuyn = models.IntegerField()
    hperyn = models.IntegerField()
    hpgryn = models.IntegerField()
    hpicuyn = models.IntegerField()
    hpnicuyn = models.IntegerField()
    hpopyn = models.IntegerField()
    
    class Meta:
        db_table = "HOSPITAL_DETAIL_INFO"
        
class HospitalRealTime(models.Model):
    hpid = models.CharField(max_length = 10, primary_key = True)
    phpid = models.CharField(max_length = 10)
    hvidate = models.CharField(max_length = 14)
    hvec = models.CharField(max_length = 4)
    hvoc = models.CharField(max_length = 4)
    hvcc = models.CharField(max_length = 4)
    hvncc = models.CharField(max_length = 4)
    hvccc = models.CharField(max_length = 4)
    hvicc = models.CharField(max_length = 4)
    hvgc = models.CharField(max_length = 4)
    hvdnm = models.CharField(max_length = 20, null = True)
    hvctayn = models.CharField(max_length = 1)
    hvmriayn = models.CharField(max_length = 1)
    hvangioayn = models.CharField(max_length = 1)
    hvventiayn = models.CharField(max_length = 1)
    hvventisoayn = models.CharField(max_length = 2)
    hvincuayn = models.CharField(max_length = 2)
    hvcrrtayn = models.CharField(max_length = 2)
    hvecmoayn = models.CharField(max_length = 2)
    hvoxyayn = models.CharField(max_length = 2)
    hvhypoayn = models.CharField(max_length = 2)
    hvamyn = models.CharField(max_length = 1)
    hv1 = models.CharField(max_length = 20, null = True)
    hv2 = models.CharField(max_length = 20, null = True)
    hv3 = models.CharField(max_length = 20, null = True)
    hv4 = models.CharField(max_length = 20, null = True)
    hv5 = models.CharField(max_length = 20, null = True)
    hv6 = models.CharField(max_length = 20, null = True)
    hv7 = models.CharField(max_length = 20, null = True)
    hv8 = models.CharField(max_length = 20, null = True)
    hv9 = models.CharField(max_length = 20, null = True)
    hv10 = models.CharField(max_length = 20, null = True)
    hv11 = models.CharField(max_length = 20, null = True)
    hv12 = models.CharField(max_length = 20, null = True)
    hv13 = models.CharField(max_length = 20, null = True)
    hv14 = models.CharField(max_length = 20, null = True)
    hv15 = models.CharField(max_length = 20, null = True)
    hv16 = models.CharField(max_length = 20, null = True)
    hv17 = models.CharField(max_length = 20, null = True)
    hv18 = models.CharField(max_length = 20, null = True)
    hv19 = models.CharField(max_length = 20, null = True)
    hv21 = models.CharField(max_length = 20, null = True)
    hv22 = models.CharField(max_length = 20, null = True)
    hv23 = models.CharField(max_length = 20, null = True)
    hv24 = models.CharField(max_length = 20, null = True)
    hv25 = models.CharField(max_length = 20, null = True)
    hv26 = models.CharField(max_length = 20, null = True)
    hv27 = models.CharField(max_length = 20, null = True)
    hv28 = models.CharField(max_length = 20, null = True)
    hv29 = models.CharField(max_length = 20, null = True)
    hv30 = models.CharField(max_length = 20, null = True)
    hv31 = models.CharField(max_length = 20, null = True)
    hv32 = models.CharField(max_length = 20, null = True)
    hv33 = models.CharField(max_length = 20, null = True)
    hv34 = models.CharField(max_length = 20, null = True)
    hv35 = models.CharField(max_length = 20, null = True)
    hv36 = models.CharField(max_length = 20, null = True)
    hv37 = models.CharField(max_length = 20, null = True)
    hv38 = models.CharField(max_length = 20, null = True)
    hv39 = models.CharField(max_length = 20, null = True)
    hv40 = models.CharField(max_length = 20, null = True)
    hv41 = models.CharField(max_length = 20, null = True)
    hv42 = models.CharField(max_length = 20, null = True)
    hv43 = models.CharField(max_length = 20, null = True)
    dutyname = models.CharField(max_length = 100, null = True)
    dutytel3 = models.CharField(max_length = 14, null = True)
    hvs01 = models.CharField(max_length = 20)
    hvs02 = models.CharField(max_length = 20, null = True)
    hvs03 = models.CharField(max_length = 20, null = True)
    hvs04 = models.CharField(max_length = 20, null = True)
    hvs05 = models.CharField(max_length = 20, null = True)
    hvs06 = models.CharField(max_length = 20, null = True)
    hvs07 = models.CharField(max_length = 20, null = True)
    hvs08 = models.CharField(max_length = 20, null = True)
    hvs09 = models.CharField(max_length = 20, null = True)
    hvs10 = models.CharField(max_length = 20, null = True)
    hvs11 = models.CharField(max_length = 20, null = True)
    hvs12 = models.CharField(max_length = 20, null = True)
    hvs13 = models.CharField(max_length = 20, null = True)
    hvs14 = models.CharField(max_length = 20, null = True)
    hvs15 = models.CharField(max_length = 20, null = True)
    hvs16 = models.CharField(max_length = 20, null = True)
    hvs17 = models.CharField(max_length = 20, null = True)
    hvs18 = models.CharField(max_length = 20, null = True)
    hvs19 = models.CharField(max_length = 20, null = True)
    hvs20 = models.CharField(max_length = 20, null = True)
    hvs21 = models.CharField(max_length = 20, null = True)
    hvs22 = models.CharField(max_length = 20, null = True)
    hvs23 = models.CharField(max_length = 20, null = True)
    hvs24 = models.CharField(max_length = 20, null = True)
    hvs25 = models.CharField(max_length = 20, null = True)
    hvs26 = models.CharField(max_length = 20, null = True)
    hvs27 = models.CharField(max_length = 20, null = True)
    hvs28 = models.CharField(max_length = 20, null = True)
    hvs29 = models.CharField(max_length = 20, null = True)
    hvs30 = models.CharField(max_length = 20, null = True)
    hvs31 = models.CharField(max_length = 20, null = True)
    hvs32 = models.CharField(max_length = 20, null = True)
    hvs33 = models.CharField(max_length = 20, null = True)
    hvs34 = models.CharField(max_length = 20, null = True)
    hvs35 = models.CharField(max_length = 20, null = True)
    hvs36 = models.CharField(max_length = 20, null = True)
    hvs37 = models.CharField(max_length = 20, null = True)
    hvs38 = models.CharField(max_length = 20, null = True)
    hvs46 = models.CharField(max_length = 20, null = True)
    hvs47 = models.CharField(max_length = 20, null = True)
    hvs48 = models.CharField(max_length = 20, null = True)
    hvs49 = models.CharField(max_length = 20, null = True)
    hvs50 = models.CharField(max_length = 20, null = True)
    hvs51 = models.CharField(max_length = 20, null = True)
    hvs52 = models.CharField(max_length = 20, null = True)
    hvs53 = models.CharField(max_length = 20, null = True)
    hvs54 = models.CharField(max_length = 20, null = True)
    hvs55 = models.CharField(max_length = 20, null = True)
    hvs56 = models.CharField(max_length = 20, null = True)
    hvs57 = models.CharField(max_length = 20, null = True)
    hvs58 = models.CharField(max_length = 20, null = True)
    hvs59 = models.CharField(max_length = 20, null = True)
    dt = models.DateTimeField()
    
    class Meta:
        db_table = "REAL_TIME_DATA"